### ISSUE TITLE
Fasta header line formats

### ISSUE THREAD

**Issue by HankewieDanke** [oxpig/ImmuneBuilder#1]
Thank you for providing this tool.

I have a small comment/request that would, I think help usability of the command-line versions of the tool.

Currently *only* `fasta` files with following format are allowed:
```
>H
YOURSEQUENCEHERE
```

I think putting this in the description would be helpful.

Best wishes

**Comment by brennanaba** [comment]
Hi @HankewieDanke 

Thanks for the suggestion, I will add some info on this to the README
