### ISSUE TITLE
[FEATURE] PDB Blacklist

### ISSUE THREAD

**Issue by frenko** [oxpig/ImmuneBuilder#2]
As the TCRBuilder webserver is it possible to add a flag to set pdbs not to be used as templates in tcr modeling?

**Comment by brennanaba** [comment]
Hi @frenko 

The original version of TCRBuilder was a homology modelling tool where the structural model was created by combining fragments from experimentally resolved PDB structures. The blacklist meant that fragments from these structures could not be used. TCRBuilder2 is a deep learning model and it is therefore not possible to blacklist PDB codes. 

All the best,

Brennan
