### ISSUE TITLE
[FEATURE] allow specifying the index of cuda device and do not set globally torch.DoubleTensor as default

### ISSUE THREAD

**Issue by adrienchaton** [oxpig/ImmuneBuilder#4]
Hello

Thank you for open sourcing your models !

Minor suggestions I may think of:

setting torch.DoubleTensor as default in e.g.
https://github.com/oxpig/ImmuneBuilder/blob/main/ImmuneBuilder/ABodyBuilder2.py#L11
is a little unpractical when imported within other code bases that are very likely to use single precision
would you think it is safe otherwise to run your model in single precision or accuracy is impacted at inference time ?

it would be also practical to give an argument to the model init for choosing which cuda device to use instead of 0 by default
https://github.com/oxpig/ImmuneBuilder/blob/main/ImmuneBuilder/NanoBodyBuilder2.py#L90
e.g. device = torch.device(f"cuda:{cuda_device}" if (torch.cuda.is_available()) else "cpu")

We could make a PR if you want
Cheers

**Comment by brennanaba** [comment]
Hi @adrienchaton 

I haven't tested running it with single precision after training so I am reluctant to make this the default. Feel free to swap to single precision and let me know how it goes.

If you could submit a PR for the second case that would be great.

All the best,

Brennan
